# Generated by Django 2.2.6 on 2019-10-23 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191023_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('state', models.BooleanField(verbose_name='Новый')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
    ]
